import type { Metadata } from "next";
import React from "react";
import "@/styles/global.scss";
export const metadata: Metadata = {
  title: "Lobanoff",
  description: "Generated by lobanoff",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
